### ISSUE TITLE
Increase scrollbar widths

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/client#1094]
A user requested to increase scroll bar width in tagging screen.
@eoglethorpe , I suggest increasing the width, but we should do it throughout the website.
Let us know what you think.

**Comment by frozenhelium** [comment]
### Current
![2020-09-25-132514.png](https://zube.io/files/deep/7d7059dcc247531048eda66773d9e737-2020-09-25-132514.png)
### Browser Default
![2020-09-25-132551.png](https://zube.io/files/deep/75f581862aa6e8574d33b242395e848b-2020-09-25-132551.png)
### Medium
![2020-09-25-132534.png](https://zube.io/files/deep/269b33f473549d621c679145699f5a51-2020-09-25-132534.png)

@eoglethorpe These are some screenshots for the size of the scrollbar. Let us know your thought.
CC: @AdityaKhatri

**Comment by eoglethorpe** [comment]
@frozenhelium thanks for these. would you mind sending along screenshots of the overivew page for these toolbars? in particular from simplified view

**Comment by eoglethorpe** [comment]
from jose:

"the widest as long as it doesn't disturb the general view. That's why I say that those I consider "important" to be wide are the one at the right side, the horizontal one and the one in the entries box at the left (in simplified view). Those  in the middle (demographic groups, affected groups, location, specific needs groups...etc.) we don't use the scrolling at all. So those could be maintained thinner if making all them wider has a bad effect on how the interface looks"

**Comment by frozenhelium** [comment]
@eoglethorpe Here you go

### Current
![2020-09-28-143742.png](https://zube.io/files/deep/6a6d01ff2aa77c47883b6d2d28fbe302-2020-09-28-143742.png)
![2020-09-28-143732.png](https://zube.io/files/deep/4486eedf8bcf090bc715b422e6e9030f-2020-09-28-143732.png)

### Medium
![2020-09-28-143706.png](https://zube.io/files/deep/ad0b5e7505098456fa0c3d0c2f169d14-2020-09-28-143706.png)
![2020-09-28-143657.png](https://zube.io/files/deep/4924eb21d44c0029f886578d3b094a19-2020-09-28-143657.png)

### Browser Default
![2020-09-28-143622.png](https://zube.io/files/deep/a1fbc61bd161c250892b091b32e22478-2020-09-28-143622.png)
![2020-09-28-143639.png](https://zube.io/files/deep/2cfb1b6283a4f39192153f3333f113ef-2020-09-28-143639.png)

I think we should keep the width of the scrollbar consistent throughout the site. Should we go with the widest one (Browser default) then?

**Comment by eoglethorpe** [comment]
thanks @frozenhelium - agree to use throuhgout the site. waiting to get some userfeedback, then i'll get back to you

**Comment by AdityaKhatri** [comment]
Go with `medium`
