### ISSUE TITLE
Change wording of notifications to consider filters

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/client#1144]
No notifications to display. Have you tried a different date range?

**Comment by eoglethorpe** [comment]
with up arrow :D

**Comment by AdityaKhatri** [comment]
@eoglethorpe , what do you think?

![image.png](https://zube.io/files/deep/eca8e2a4440a27085e9960dea341b915-image.png)

**Comment by eoglethorpe** [comment]
Yep looks good!
