### ISSUE TITLE
User exports: Show proper export status

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/client#1188]
Add helpful tooltips aswell

**Comment by AdityaKhatri** [comment]
@eoglethorpe , @jbbove , while we are waiting for the new user exports' wireframes, we thinking showing appropriate status should be done.
Let us know if you think otherwise.

**Comment by eoglethorpe** [comment]
@AdityaKhatri sure, that's fine for me. @jbbove do we know what these would be? (cc @Mariam-Asatryan )
