### ISSUE TITLE
Table of contents: Expand/collapse whole tree

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/client#1209]
**User story:**
As a Quality Controller, I need to be able to expand/collapse the Table of Contents Tree to minimize the scrolling while I filter the entries based on the sectors and sub-sectors of the Analytical Framework.

**AC:**
Table of content is expandable/collapsable and presents the sectors and sub-sectors of the AF in a structured way, visually clear and that enables easy multi selection.

**Comment by AdityaKhatri** [comment]
As a user, I would like to be able to expand and collapse the Table of Contents with a button right next to title of ToC.

**Comment by elishadhungana** [comment]
Tested by QA

**Comment by elishadhungana** [comment]
Tested By QA
