### ISSUE TITLE
Entry Card: Hide bottom details after `excerpt` and only show on hover / click

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/client#1218]
Currently, only the actions are hidden.
Now, all the items after excerpt view should only be shown on hover.

**User Story**
As a quality controller, I would like to see only the most relevant information on an entry card and only see details while hovering on the card to be able to focus my attention and discard noise.

**Acceptance Criteria**
Items we keep:
Lead title, excerpt, status of entry, 

Items we show only while hovering:
All the action buttons except the box to verify, assignee, date uploaded, authoring org, date of publication, scale widgets

**Comment by jbbove** [comment]
**User Story**
As a quality controller, I would like to see only the most relevant information on an entry card and only see details while hovering on the card to be able to focus my attention and discard noise.

**Acceptance Criteria**
Items we keep:
Lead title, excerpt, status of entry, 

Items we show only while hovering:
All the action buttons except the box to verify, assignee, date uploaded, authoring org, date of publication, scale widgets

**Comment by jbbove** [comment]
Question: 
Since Patrice wants a way to quickly see the tag of an entry in the card to modify 'on the fly' and easily identify mistakes, couldn't we use the space we have freed with this task to show the most important tags? @AdityaKhatri let's discuss this

**Comment by AdityaKhatri** [comment]
Hi @jbbove , it won't be possible as we wouldn't know what is important and what is not.
Also, almost all of the widgets are large and will be difficult to fit in a smaller place.
