### ISSUE TITLE
Entry card: Increase size of screenshot popup to maximum

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/client#1219]

**Comment by jbbove** [comment]
The screenshot is pretty big already, do we really want to make it completely full screen? How does the user go back to entries page if it is full screen? what happens with the resolution if we increase to full screen? I have doubts on this one
![Screen Shot 2020-12-01 at 12.13.40.png](https://zube.io/files/deep/169b71edaa4922e438f7a5db18bb0d02-screen-shot-2020-12-01-at-12-13-40.png)

**Comment by AdityaKhatri** [comment]
Hi @jbbove , it appears small in 1080x1920 resolution which is used by a lot of deep taggers at the moment.
We would like to make it similar to what you are seeing currently as well but for all resolutions.
