### ISSUE TITLE
Quality Control: Show/hide ToC

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/client#1221]

**Comment by jbbove** [comment]
**User Story**
As a quality controller I would like to be able to hide the ToC in the QC page to be able to see only the entries on my screen.

**Acceptance Criteria**
Similarly to how Google Docs hides the ToC of a document, an action button (an arrow in Gdocs) allows users to hide the ToC and another action button (a ToC icon in GDocs) allows users to bring it back
![Screen Shot 2020-12-01 at 11.26.08.png](https://zube.io/files/deep/be17161189918eb99a24aed84b57e0a9-screen-shot-2020-12-01-at-11-26-08.png)![Screen Shot 2020-12-01 at 11.27.27.png](https://zube.io/files/deep/f1792e9b92cb72bde6db72d0d1a7d74e-screen-shot-2020-12-01-at-11-27-27.png)

**Comment by elishadhungana** [comment]
Tested By QA
