### ISSUE TITLE
Quality Control: Remove list item dots from header

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/client#1222]
![image.png](https://zube.io/files/deep/a909b94c2bb418624a395c1b4e7460bf-image.png)

**Comment by jbbove** [comment]
What's this?

**Comment by AdityaKhatri** [comment]
@jbbove , this refers to removing the small gray icon left to `Raven`.

**Comment by elishadhungana** [comment]
Tested by QA![dot.JPG](https://zube.io/files/deep/b7f935c83c231bb589b9138d085cbeb3-dot.jpg)
