### ISSUE TITLE
Export UI: UI cleanup and label changes

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/client#1279]
Items to be completed:

1. Select Source(S) -> no capital S
2. Separating the Search Bar from the leads/entries filters (one line for the search bar, one line for the filters
3. Show only the 4 most important filters in the filters line -> for now we can stick to Tagging Status (which corresponds to our Lead Status), Published On, Tagged On (which would be our Created On), Assignee. 
4. Place the button ‘Show All Filters’ on the right in the same line as those 4 most important filters
5. Sources table: show exactly the same columns as in the prototype (we are currently showing the only Title and Created At) + show the number of entries per source as in the prototype
6. In user exports show appropriate message next to the state of export as in the mockups

**Comment by jbbove** [comment]
@AdityaKhatri shouldn't we wait this one as well is completed before we push the changes to beta?
