### ISSUE TITLE
Analysis Module: Create analyses card

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/client#1337]
![image.png](https://zube.io/files/deep/bee9752356154da46a710a314e68460d-image.png)
We don't include team lead, framework, sources analyzed, date, and list of analytical statements.

**Comment by jbbove** [comment]
Units:
entries analyzed = #of entries in an analytical statement column + #of entries discarded / total entries in the beginning of an analysis
I don't think it is useful to show the sources analysed, it is better to show multiple progress bars with entries analysed for each sector of the analytical framework
