### ISSUE TITLE
Exports: Fix Additional Context in Word Export

### ISSUE THREAD

**Issue by subinasr** [the-deep/client#1482]
Additional Context is being elevated to a "header" level when actually we just want it to appear as normal text following the entry itself. \It would be great if we can have the text appear like this:

"Additional context: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor."

Immediately after the excerpt and before the bibliography information that appears in parentheses.

**Comment by kumud02** [comment]
Description is displayed as normal text. 
![image.png](https://zube.io/files/deep/8d6452023d0bdf8866078d76b9920523-image.png)
