### ISSUE TITLE
New Project Flow: Project Details Page > Style stakeholders Add button

### ISSUE THREAD

**Issue by samshara** [the-deep/client#1517]
![Screenshot from 2021-04-16 10-17-32.png](https://zube.io/files/deep/769a284199564fe390db639ca60bbacd-screenshot-from-2021-04-16-10-17-32.png)

**Comment by subinasr** [comment]
Checked in alpha1 server. Seems like this functionality has already been implemented. Please re-verify this.
CC: @Suraj-Shrestha @kumud02  @AdityaKhatri

**Comment by suraj-ram-shrestha** [comment]
Checked in alpha1 server. Seems like this functionality has already been implemented. Please re-verify this.

CC: @Suraj-Shrestha @kumud02 @AdityaKhatri
