### ISSUE TITLE
New Project Flow: Project Details Page > popup hints for specific options and values as shown in Figma prototype

### ISSUE THREAD

**Issue by samshara** [the-deep/client#1523]
Reach out to Jean for each specific infoboxes.

**Comment by subinasr** [comment]
![image.png](https://zube.io/files/deep/e1e43601cc1663b6e8ac581017a2a800-image.png)

@jbbove Can you mention what you need in the popup hints in each of these checkboxes?

**Comment by jbbove** [comment]
Hi @Subina-Sharma-Rajopadhyaya 
I need to think about it, could you please fill in random text for now?

**Comment by subinasr** [comment]
Sure @jbbove . I'll make the layout for now, let me know when you come up with the content.
