### ISSUE TITLE
Word export: Research on if we can generate google docs links

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/client#1595]

**Comment by suraj-ram-shrestha** [comment]
> NOTE: Maximum hour for research = 4 hr

**Comment by thenav56** [comment]
Google API provides API endpoints. Detailed documentation can be found here https://developers.google.com/docs/api/reference/rest/v1/documents
It also provides bulk action endpoint as well https://developers.google.com/docs/api/reference/rest/v1/documents/batchUpdate#InsertTextRequest

To go into detail on find "If we can generate google docs links" we need to go in-depth to underline what specific word action we require like add_text, add_image,
add a hyperlink, add spacing, etc. This will require a breakdown of tickets for the following.
- Listing word actions we need. (Also, in future)
- Map those actions with google doc API. https://developers.google.com/docs/api/reference/rest/v1/documents
- Implement google doc export if we have a well-detailed green report with the above.


To note
- Hitting an endpoint will be slower than write to disk/memory adding additional export time.
- There can be storage issues when using Google Docs as storage in google drive is expensive than s3.
