### ISSUE TITLE
Analytical Framework: Add file input in framework form

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/client#1672]
* Make it compatible with form and send the data to server
* Show image in form using a separate preview
* Show image in framework viewing page (top bar)
* Show image in framework editing page (top bar)

**Comment by suraj-ram-shrestha** [comment]
NOTE: Moving to next sprint since we have to create DEEP file input.

**Comment by tnagorra** [comment]
1. Let's just use simple FileInput.
2. We can send "null/undefined" to the server when we don't want to change the image.
3. We can use File descriptor or the url from server to show the preview.
4. FileInput should only handle File object. (string should not be passed to FileInput)
