### ISSUE TITLE
Home Page: Check logic to calculate sources tagged percentages

### ISSUE THREAD

**Issue by suraj-ram-shrestha** [the-deep/client#1704]
![Screen Shot 2021-06-07 at 2.33.36 PM.png](https://zube.io/files/deep/b307f633d8cd897c5b5befb7d51c9634-screen-shot-2021-06-07-at-2-33-36-pm.png)

## Feedback from client

* Why do I get a count of 100% sources tagged in the summary of my projects statistic if I have a project (GIMAC test) that has 0% sources tagged? - Fix logic to calculate sources tagged percentages.

**Comment by samshara** [comment]
@AdityaKhatri ,@Suraj-Shrestha , I couldn't exactly replicate this behavior in the client. However, we can get a scenario mentioned as above if the totalSources = 0, and sourcesTagged = 1 (arbitary value), now the percentage is calculated as infinity. This should not happen. I think we should revisit the calculation of these values in server and verify that the sourcesTagged value is always less thanor equal totalSources. (Note: the calcuation of statistics are done in batches so the user might see previous values)
