### ISSUE TITLE
Analysis Module: Clean up minor feed backs in Analysis dashboard

### ISSUE THREAD

**Issue by suraj-ram-shrestha** [the-deep/client#1715]
## Acceptance Criteria
* Analysis>Header>ProjectDropdown: Edit button on the side of project to edit it
* Analysis>Pie Chart: Number precision on piechart should be 2
* Analysis Item: Show “Edit analysis” label on edit button
* Analysis Item:Pillar Item: Show “Continue analysis/Edit analysis” label on edit button (depending on completed)
* Analysis Item:Pillar Item: Show pillar as completed based on completion percentage
* Dashboard: Add name of framework used when clicked should open the image of the associated framework
* Dashboard: Label below pie chart is missing
* Fix overflowing label in pie chart

**Comment by AdityaKhatri** [comment]
Remaining:
Analysis>Header>ProjectDropdown: Edit button on the side of project to edit it
