### ISSUE TITLE
Tagging Page: PageNavbar

### ISSUE THREAD

**Issue by suraj-ram-shrestha** [the-deep/client#1751]
![Screen Shot 2021-06-11 at 3.09.30 PM.png](https://zube.io/files/deep/1743cfa599b96ac6c74328066b09d01f-screen-shot-2021-06-11-at-3-09-30-pm.png)

## Acceptance Criteria
- Add a project selection
  - Create and use search select for project selection
- Edit currently selected project (link to edit project page)
    - Use Cloak
- Add links to Source, Dashboard, Export
    - Use Cloak
- Add a dropdown for "add a source"
   - Open bulk upload modal (page or modal)
   - Open new connector modal (page or modal)
- Add a button to open connectors (sources from connectors)
  - Disable for now

### Attachments
- [Figma Link](https://www.figma.com/proto/HaQd4COVlpSMoqSfgL5ZDx/DEEP_UI_LIBRARY-%5Bin-progress%5D?node-id=6887%3A11402&scaling=scale-down)

**Comment by tnagorra** [comment]
The mockup has changed. So, we can only partly complete this task
