### ISSUE TITLE
Fetch framework details and show primary tagging canvas

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/client#1938]
![image.png](https://zube.io/files/deep/c5d4e48b431a01a062b25acd7001e01f-image.png)

### New Addition
* Fetch framework details and show primary tagging canvas

### Attachments
- [Figma Link](https://www.figma.com/proto/HaQd4COVlpSMoqSfgL5ZDx/DEEP_UI_LIBRARY-%5Bin-progress%5D?node-id=6869%3A90&scaling=min-zoom)

**Comment by suraj-ram-shrestha** [comment]
@AdityaKhatri @frozenhelium @tnagorra 
Blocked because we can't create framework

**Comment by frozenhelium** [comment]
We do not have a mechanism to create a framework yet, so we won't be able to test it out if it works!
