### ISSUE TITLE
Fetch framework details and show secondary tagging canvas

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/client#1939]
![image.png](https://zube.io/files/deep/4f2291e17d4ef127ee9926a57361a22f-image.png)

## Acceptance Criteria

* Show secondary tagging canvas for selected entry

## Attachments

- [Figma Link](https://www.figma.com/proto/HaQd4COVlpSMoqSfgL5ZDx/DEEP_UI_LIBRARY-%5Bin-progress%5D?node-id=6887%3A1438&scaling=min-zoom)

**Comment by frozenhelium** [comment]
We do not have a mechanism to create a framework yet, so we won't be able to test it out if it works!
