### ISSUE TITLE
Create spinner component

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/client#1969]
### New Addition
* Add a spinner component that can be used to show progress and can be used inside tag

**Comment by frozenhelium** [comment]
@AdityaKhatri  Do we have specific design for this?

Is it different from: https://github.com/the-deep/deep-ui/blob/develop/src/components/PendingAnimation/index.tsx

**Comment by AdityaKhatri** [comment]
@frozenhelium , we need to use it inside tags as:
![image.png](https://zube.io/files/deep/270d5538d92b55be38a77223173f6437-image.png)
