### ISSUE TITLE
Add conditions modal

### ISSUE THREAD

**Issue by tnagorra** [the-deep/client#2240]
- Let user select parent widget
    - The parent widget can be parent to other child widgets.
    - The parent widget cannot be itself.
    - The parent widget cannot be a child widget to another parent widget.
    - The parent widget should be scoped by section and primary/secondary tagging.

- After user selects a parent widget, a "default" condition item should be created
    - the "conditions" depends on the type of parent widget selected

- When "type" of "condition" is changed, the user defined values should be cleared.
- "delete" button should be shown to delete existing condition
- The "conditions" should be orderable
- Pressing on "and/or/xor" button should add a new condition item
- There should be at least one condition item

- User should be able to clear parent widget and all associated conditions

**Comment by kumud02** [comment]
QA Verified!
