### ISSUE TITLE
Error while saving entries because of duplicate clientId

### ISSUE THREAD

**Issue by tnagorra** [the-deep/client#2279]

**Comment by thenav56** [comment]
@AdityaKhatri @tnagorra This is fixed on the client-side right?

**Comment by thenav56** [comment]
If this occurs again. We will remove the clientId from database.

**Comment by tnagorra** [comment]
This should be fixed from the server side.
Client is sending the data correctly.

**Comment by thenav56** [comment]
@AdityaKhatri  @tnagorra Haven't seen this issue again. Should we close this issue? cc: @udaynwa

**Comment by thenav56** [comment]
cc: @kumud02

**Comment by kumud02** [comment]
The issue is not seen by the QA team and from the other users too. 
Task is closed for now.
