### ISSUE TITLE
More than 11 sub columns are not present while tagging

### ISSUE THREAD

**Issue by udaynwa** [the-deep/client#2576]
**Steps to Reproduce:**
1. Go to Analytical framework
2. Add columns and sub-columns in 2d ( sub columns more than twelve)
3. Go to the Entry Tagging page
4. Try to tag on 2d

![image.png](https://zube.io/files/deep/f167fe45dc7bcb16f9146c6025cbe900-image.png)
![image.png](https://zube.io/files/deep/f10a85e7c72d2de3978a088ec33bcad5-image.png)

**Comment by subinasr** [comment]
Cannot replicate
